src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Cocur\Slugify\Slugify;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Vich\Uploadable
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(
     *     min=3
     *     )
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(
     *     min=10
     *     )
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $cover;

    /**
     * @Vich\UploadableField(mapping="aticles_img", fileNameProperty="cover")
     * @Assert\File(
     *     maxSize = "1024k",
     *     mimeTypes = {"image/jpeg", "image/png"},
     *     mimeTypesMessage = "SVP Image au format jpeg, png d'une taille max 1MO"
     * )
     * @var File
     */
    private $imageFile;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $update_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCover(): ?string
    {
        return $this->cover;
    }

    public function setCover(?string $cover): self
    {
        $this->cover = $cover;

        return $this;
    }

    public function getDateCreated(): ?\DateTimeInterface
    {
        return $this->date_created;
    }

    public function setDateCreated(\DateTimeInterface $date_created): self
    {
        $this->date_created = $date_created;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->update_at;
    }

    public function setUpdateAt(?\DateTimeInterface $update_at): self
    {
        $this->update_at = $update_at;

        return $this;
    }

    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param File $imageFile
     */
    public function setImageFile(File $imageFile = null)
    {
        $this->imageFile = $imageFile;
        if ($imageFile) {
            $this->update_at = new \DateTime('now');
        }
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('content')
            ->add('imageFile', FileType::class, [
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/article")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="article_index", methods={"GET"})
     */
    public function index(ArticleRepository $articleRepository): Response
    {
        return $this->render('pages/home.html.twig', [
            'articles' => $articleRepository->findBy([], ["date_created" => "DESC"]),
        ]);
    }

    /**
     * @Route("/new", name="article_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $article->setDateCreated(new \DateTime());
            $entityManager->persist($article);
            $entityManager->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}-{slug}", name="article_show", methods={"GET"})
     */
    public function show(Article $article): Response
    {
        return $this->render('pages/article.html.twig', [
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="article_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="article_delete", methods={"POST"})
     */
    public function delete(Request $request, Article $article, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $entityManager->remove($article);
            $entityManager->flush();
        }

        return $this->redirectToRoute('article_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/article/_delete_form.html.twig
<form method="post" action="{{ path('article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/article/_form.html.twig
{% form_theme form 'bootstrap_4_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_rest(form) }}
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <div class="jumbotron" style="background: #E4E6EC">
        <div class="container">
            <h1>Edit Article</h1>
            {{ include('article/_form.html.twig', {'button_label': 'Update'}) }}
            <div class="row">
                <div class="col">
                    {{ include('article/_delete_form.html.twig') }}
                </div>
                <div class="col">
                    <a href="{{ path('article_index') }}">back to list</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <div class="jumbotron" style="background: #E4E6EC">
        <div class="container">
            <h1>Create new Article</h1>
            {{ include('article/_form.html.twig') }}
            <a href="{{ path('article_index') }}">back to list</a>
        </div>
    </div>
{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Blog{% endblock %}</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@300;800&family=Roboto:ital,wght@0,400;0,900;1,300&display=swap" rel="stylesheet">
    <link href="https://fr.allfont.net/allfont.css?fonts=roboto-black" rel="stylesheet" type="text/css" />
    <link href="https://fr.allfont.net/allfont.css?fonts=roboto-regular" rel="stylesheet" type="text/css" />
    <link href="https://fr.allfont.net/allfont.css?fonts=roboto-light-italic" rel="stylesheet" type="text/css" />
    <link href="https://fr.allfont.net/allfont.css?fonts=roboto-slab-bold" rel="stylesheet" type="text/css" />
    {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
    {% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
    {% endblock %}
</head>
<body>
<header>
    <a href="{{ path('article_index') }}" style="text-decoration: none">
        <div>
            <img src="/img/logo.png">
            <p>SpaceBlog</p>
        </div>
    </a>
</header>
{% block body %}{% endblock %}
<footer>
    <div>
        <svg xmlns="http://www.w3.org/2000/svg" width="169.787" height="147.681" viewBox="0 0 169.787 147.681">
            <path id="Tracé_3" data-name="Tracé 3" d="M125.354-55.821c-12.737,1.128-28.161,7.2-43.419,17.082-5.9,3.881-6.667,4.544-6.667,6.136a2.73,2.73,0,0,0,2.123,2.819c.829.2,1.327-.033,6.932-2.952a36.742,36.742,0,0,1,16.153-4.412c6.2-.3,10.15.829,13.069,3.748,2.952,2.919,3.781,7.563,2.72,15.026-2.886,19.8-13.5,38.377-30.383,53.2-12.107,10.614-22.854,15.789-32.8,15.789-8.558-.033-13.5-3.781-15.125-11.51a23.605,23.605,0,0,1-.5-4.013c0-1.426-.166-1.924-.829-2.554-1.26-1.294-2.654-1.128-4.213.531-3.018,3.184-5.042,9.486-5.539,17.381L26.642,54.1,25.58,51.946C18.88,38.081,22.3,16.222,35-8.389A45.536,45.536,0,0,0,37.455-13.6a3.057,3.057,0,0,0-2.985-2.786c-1.294,0-6.5,3.914-9.984,7.529C18.847-2.949,14.7,3.32,9.427,13.967,2.694,27.6.571,34.565.073,44.682-.491,56.589,3.025,68.431,9.56,76.557A38.106,38.106,0,0,0,32.446,90.588c14.727,3.052,32.44-1.128,51.976-12.273A185.616,185.616,0,0,0,103.3,65.446a136.734,136.734,0,0,0,21.593-21.958c11.576-14.827,20.465-34.363,23.683-52.109,1.028-5.771.929-5.572,1.857-3.35,5.838,13.832,2.886,34.4-8.027,55.99-2.289,4.478-2.289,5.705,0,6.6,1.393.531,2.753-.3,5.9-3.582,14.23-14.827,23.285-41.263,21.2-61.927-1.327-12.87-5.274-22.124-12.9-30.085-6.4-6.667-13.2-9.951-22.588-10.88A32.857,32.857,0,0,0,125.354-55.821Z" transform="translate(-0.014 56.124)" fill="#fff"/>
            <path id="Tracé_4" data-name="Tracé 4" d="M59.29-45.523A48.159,48.159,0,0,0,43.932-37.53,76.206,76.206,0,0,0,32.389-25.29c-2.62,3.615-5.506,9.453-6.269,12.638-.73,2.985-.73,7.795-.033,9.785,1.426,3.914,4.511,6.2,8.956,6.7l1,.1-1.36.929C30.532,7.713,25.49,7.216,23.732,3.733A14.862,14.862,0,0,1,22.5-4.095c.2-2.222.166-2.421-.63-3.217a2.62,2.62,0,0,0-3.781-.133c-.829.9-2.554,5.871-3.085,8.889a30.42,30.42,0,0,0,.166,10.448c1.26,4.677,4.047,8.359,7.728,10.183,2.056,1.028,2.421,1.095,5.539,1.061a13.816,13.816,0,0,0,5.771-.9C44.1,18.659,52.556,10.3,58.593-1.906c3.184-6.4,4.013-9.287,4.013-13.732,0-3.317-.066-3.814-.9-5.34a10.792,10.792,0,0,0-5.606-4.909,10.135,10.135,0,0,1-2.057-.862c-.166-.133,1.294-1.028,3.251-1.99,8.558-4.179,11.775-1.592,11.775,9.52,0,3.018.066,3.35.763,4.013a2.84,2.84,0,0,0,3.45.232,13.224,13.224,0,0,0,2.023-3.217C80.352-28.541,78-41.543,70.468-45.225,67.781-46.519,63.1-46.651,59.29-45.523Z" transform="translate(26.744 74.12)" fill="#fff"/>
        </svg>
        <p>SpaceBlog</p>
    </div>
</footer>
</body>
</html>

templates/pages/article.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <article>
        <a href="{{ path('article_index') }}" class="back">
            <button>
                Retour
            </button>
        </a>
        <div class="container-article">
            {% if article.cover %}
                <img src="/img/articles/{{ article.cover }}" width="1000">
            {% else %}
                <img src="/img/logo.png" width="1000">
            {% endif %}
            <h1>{{ article.title }}</h1>
            <p class="content"> {{ article.content }}</p>
            <p class="date">Publié le {{ article.dateCreated | date('d/m/Y à H\\hi') }}</p>
        </div>
        <a href="{{ path('article_edit', {'id': article.id}) }}" class="back">
            <button style="margin:0 0 30px 16%">
                Edit
            </button>
        </a>
    </article>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <article>
        <div class="titlePage">
            <img src="/img/fuse.png" alt="fuse" width="1280" height="420">
            <h1>DÉCOUVREZ <span>L'ESPACE</span> </br>
                COMME JAMAIS </br>
                AUPARAVANT</h1>
        </div>
        <div class="titleArticle">
            {% if articles|length > 0 %}
                <h2>Nos articles</h2>
                <div class="allArticles">
                    {% for article in articles %}
                        <a href="{{ path('article_show', {'id': article.id < 10 ? '0'~article.id : article.id, 'slug': article.slug}) }}"
                           style="text-decoration: none;">
                            <div class="article">
                                {% if article.cover %}
                                    <img src="/img/articles/{{ article.cover }}">
                                {% else %}
                                    <img src="/img/logo.png">
                                {% endif %}
                                <p>{{ article.title }}<p>
                            </div>
                        </a>
                    {% endfor %}
                </div>

            {% else %}
                <h2 style="text-align: center;margin-bottom: 20px">Il n'y a aucun article pour le moment</h2>
            {% endif %}
            <a href="{{ path('article_new') }}" class="back">
                <button style="margin: 0 0 20px 0">
                    New
                </button>
            </a>
        </div>
    </article>

{% endblock %}